drop table if exists kraje cascade;
drop table if exists miasta cascade;
drop table if exists lotniska cascade;
drop table if exists modele_samolotow cascade;
drop table if exists samoloty cascade;
drop table if exists bilety cascade;
drop table if exists bilety_laczone cascade;
drop table if exists nadanie_bagazu cascade;
drop table if exists miejsca_w_samolocie cascade;
drop table if exists linie_lotnicze cascade;
drop table if exists plany_lotow cascade;
drop view if exists loty cascade;
drop function if exists from_pln(numeric, character) cascade;
drop function if exists ortodroma(numeric, numeric, numeric, numeric) cascade;
drop function if exists ticket_cost(character, character, character varying, numeric) cascade;
drop function if exists zaplanuj_lot(bigint, text, text, timestamp without time zone) cascade;
drop function if exists znajdz_id_lotow(src text, dest text, czas timestamp without time zone) cascade;
drop function if exists znajdz_loty(src text, dest text, czas timestamp without time zone) cascade;
drop sequence if exists bilety_laczone_id_biletu_laczonego_seq cascade;
drop sequence if exists linie_lotnicze_id_linii_lotniczej_seq cascade;
drop sequence if exists miasta_id_miasta_seq cascade;
drop sequence if exists modele_samolotow_model_seq cascade;
drop sequence if exists samoloty_id_samolotu_seq cascade;
